/**
 * API types. Typed operations come from the OpenAPI contract (`schema.d.ts`, generated by
 * `pnpm gen:api` from /api/openapi.json); routes whose OpenAPI response is a free-form object
 * (snapshot, assets, KPI, lists…) are described here from the M4 contract (PROGRESS «Для M5»).
 */
import type { components } from "./schema";

type S = components["schemas"];
export type TokenView = S["TokenView"];
export type UserView = S["UserView"];
export type ForecastRunView = S["ForecastRunView"];
export type ForecastResult = S["ForecastResult"];
export type ForecastRequest = S["ForecastRequest"];
export type Overrides = S["Overrides"];
export type Quantiles = S["Quantiles"];
export type FanPoint = S["FanPoint"];
export type LeversResult = S["LeversResult"];
export type LeverResult = S["LeverResult"];
export type ShiftsNeeded = S["ShiftsNeeded"];
export type EffectResult = S["EffectResult"];
export type ReportView = S["ReportView"];
export type ClassifyBody = S["ClassifyBody"];
export type AndonBody = S["AndonBody"];
export type DefectBody = S["DefectBody"];
export type MaterialCallBody = S["MaterialCallBody"];

export type StateCode =
  | "RUNNING"
  | "DEGRADED"
  | "STARVED"
  | "BLOCKED"
  | "DOWN_UNPLANNED"
  | "DOWN_PLANNED"
  | "CHANGEOVER"
  | "IDLE_NO_PLAN";

export type Severity = "critical" | "warning" | "info";

// ------------------------------------------------------------------ assets (GET /assets)

export interface Rect {
  x: number;
  y: number;
  w: number;
  h: number;
}
export interface Named {
  name_ru: string;
  name_kk?: string | null;
}
export interface EquipmentAsset extends Named {
  code: string;
  type: string;
  criticality: "A" | "B" | "C";
  degraded_capacity: number;
  line: string;
  area: string;
  layout?: { x: number; y: number } | null;
}
export interface LineAsset extends Named {
  code: string;
  ict_seconds: number;
  plan_rate_per_shift: number;
  equipment: EquipmentAsset[];
}
export interface AreaAsset extends Named {
  code: string;
  kind: "production" | "storage";
  seq: number;
  layout?: Rect | null;
  lines: LineAsset[];
}
export interface BufferAsset extends Named {
  code: string;
  from_line: string;
  to_line: string;
  capacity: number;
  layout?: Rect | null;
}
export interface SignalSpec extends Named {
  code: string;
  unit: string;
  lo: number;
  hi: number;
  warn_lo?: number | null;
  warn_hi?: number | null;
  limit_lo?: number | null;
  limit_hi?: number | null;
}
export interface AssetsView {
  site: Named & { code: string; timezone: string; currency: string };
  calendar: {
    shifts: Array<Named & { code: string; start: string; end: string }>;
    working_weekdays: number[];
    holidays: Array<{ date: string; name_ru: string; name_kk?: string | null }>;
    extra_working_days: Array<{ date: string; shifts?: string[] | null }>;
  };
  flow: string[];
  areas: AreaAsset[];
  buffers: BufferAsset[];
  products: Array<{ code: string; name: string; color_hex: string; cycle_factor: number }>;
  equipment_types: Record<string, Named & { signals: SignalSpec[] }>;
  layout: { viewbox: number[]; flow_path: number[][] };
  plan: Array<{ month: string; level: string; line: string | null; product: string | null; qty: number }>;
}

// ------------------------------------------------------------------ references

export interface ReasonView extends Named {
  code: string;
  planned: boolean;
  bucket: string;
}
export interface ReasonCategory extends Named {
  code: string;
  reasons: ReasonView[];
}
export interface DefectCodeView extends Named {
  code: string;
  area: string;
  disposition: string;
  rework_min: number;
  repaint: boolean;
}

// ------------------------------------------------------------------ live (§12.3 + M4 extras)

export interface ShiftRef {
  date: string;
  code: string;
  elapsed_min?: number;
}
export interface KpiValues {
  pot?: number;
  pbt?: number;
  apt?: number;
  adot?: number;
  adet?: number;
  pq: number | null;
  gq: number | null;
  availability: number | null;
  effectiveness: number | null;
  quality_ratio: number | null;
  oee: number | null;
  fpy?: number | null;
  defect_rate?: number | null;
}
export interface LineLive extends KpiValues {
  code: string;
  state: StateCode | null;
  since: string | null;
  reason_code: string | null;
  plan_to_now: number | null;
  shift?: ShiftRef;
}
export interface DowntimeLive {
  entity: string;
  line: string;
  start_ts: string;
  end_ts: string | null;
  duration_min: number;
  state: StateCode;
  reason_code: string | null;
  reason_source: string | null;
  planned: boolean;
  needs_classification: boolean;
}
export interface EquipmentLive {
  code: string;
  state: StateCode | null;
  since: string | null;
  reason_code: string | null;
  health_index: number | null;
  alarm: boolean;
  alarm_code?: string | null;
  line?: string;
  downtime?: DowntimeLive | null;
}
export interface BufferLive {
  code: string;
  level: number | null;
  capacity: number | null;
  minutes_to_full: number | null;
  minutes_to_empty: number | null;
  rate_per_min?: number | null;
}
export interface AreaLive extends KpiValues {
  code: string;
  shift?: ShiftRef;
}
export interface PlantLive {
  rty: number | null;
  fg_good_shift?: number;
  fg_good_mtd?: number;
  shift?: ShiftRef;
}
export interface BottleneckLive {
  current: string | null;
  since: string | null;
  shift_shares: Record<string, { sole: number; shifting: number }>;
  shift_overall?: string | null;
}
export type AlertCounts = Record<Severity, number>;
export interface ClockLive {
  plant_time: string;
  shift: ShiftRef | null;
  speed: number;
  mode: string;
  paused?: boolean;
}
export interface Snapshot {
  clock: ClockLive | null;
  lines: LineLive[];
  equipment: EquipmentLive[];
  buffers: BufferLive[];
  bottleneck: BottleneckLive;
  alerts_open: AlertCounts;
  areas?: AreaLive[];
  plant?: PlantLive | null;
  downtime_open?: DowntimeLive[];
}
export interface UnitEvent {
  line: string;
  body_id: string;
  product: string;
  result: string;
  defect_code: string | null;
  ts: string;
}

// ------------------------------------------------------------------ lists

export interface Page<T> {
  items: T[];
  next_cursor: string | null;
}
export interface AlertView {
  id: number;
  ts: string;
  rule_id: string;
  severity: Severity;
  entity_type: string;
  entity: string;
  title_ru: string;
  title_kk: string | null;
  message_ru: string;
  message_kk: string | null;
  value: unknown;
  status: "open" | "ack" | "resolved";
  ack_by: string | null;
  ack_ts: string | null;
  escalation_level: number;
  recipients: string[];
  can_act: boolean;
}
export interface AlertsPage extends Page<AlertView> {
  open_counts: AlertCounts;
}
export interface DowntimeView {
  id: number;
  entity: string;
  entity_type: string;
  line: string;
  area: string;
  start_ts: string | null;
  end_ts: string | null;
  open: boolean;
  duration_s: number | null;
  planned: boolean;
  reason_code: string | null;
  reason_name_ru: string | null;
  reason_source: string | null;
  needs_classification: boolean;
  import_id?: number | null;
  comment?: string | null;
}

// ------------------------------------------------------------------ KPI, plan, losses

export interface KpiRow extends KpiValues {
  level: string;
  code: string;
  month?: string;
  date?: string;
  shift?: string;
  source?: string;
}
export interface KpiResponse {
  level: string;
  from: string;
  to: string;
  granularity: string;
  items: KpiRow[];
}
export interface PlanProgress {
  month: string;
  as_of: string;
  mtd_output: number;
  shifts: { total: number; elapsed: number; remaining: number };
  targets: Record<
    string,
    { qty: number; plan_to_date: number; fulfilment: number; remaining_qty: number; required_rate: number | null }
  >;
  unallocated: number;
  line_plan_by_product: Record<string, number>;
  daily: Array<{ date: string; output: number; cum_output: number; cum_plan: Record<string, number> }>;
}
export interface LossItem {
  category: string;
  line: string | null;
  area: string | null;
  reason_code: string | null;
  equipment: string | null;
  minutes: number;
  units: number;
  kzt: number;
  loss: boolean;
}
export interface LossesResponse {
  currency: string;
  kzt_per_car: number;
  assumptions: Record<string, boolean>;
  totals: { minutes: number; units: number; kzt: number };
  categories: Array<{ category: string; minutes: number; units: number; kzt: number; loss: boolean }>;
  items: LossItem[];
}
export interface BottleneckResponse {
  shares: Record<string, { sole: number; shifting: number }>;
  overall: string | null;
}

// ------------------------------------------------------------------ equipment

export interface SignalNow extends SignalSpec {
  value: number | null;
  ts: string | null;
  status: string;
}
export interface HealthView {
  code: string;
  name_ru: string;
  type: string;
  criticality: string;
  line: string;
  state: StateCode | null;
  since: string | null;
  reason_code: string | null;
  alarm: boolean;
  downtime: DowntimeLive | null;
  health_index: number | null;
  prediction: { p_failure?: number; horizon_h?: number; factors?: Array<{ text_ru?: string; text?: string }> } | null;
  signals: SignalNow[];
  reliability_30d: { failures: number; mtbf_h: number | null; mttr_min: number | null } | null;
}
export interface TelemetryView {
  agg: string;
  columns: string[];
  signals: Array<SignalSpec & { points: Array<[string, number | null, ...Array<number | null>]> }>;
}
export interface TimelineView {
  from: string;
  to: string;
  entities: Array<{
    code: string;
    entity_type: string;
    intervals: Array<{ start: string; end: string | null; state: StateCode; reason_code: string | null }>;
  }>;
}

// ------------------------------------------------------------------ import (FR-IMP-05)

export interface ImportReport {
  job: { id: number; filename: string; kind: string; status: string; created_ts: string; created: boolean };
  meta: {
    kind: string;
    files: string[];
    shift: string | null;
    period: { from: string; to: string };
    assumptions: string[];
    ict_seconds: number;
    shift_minutes: number;
  };
  shift_reports: Array<{
    date: string;
    shift: string | null;
    area: string;
    line: string;
    plan_qty: number | null;
    produced_qty: number;
    good_qty: number;
    defect_qty: number;
    lost_min: number;
    availability: number;
    effectiveness: number;
    quality_ratio: number;
    oee: number;
    defect_rate: number;
    reported_load_pct: number | null;
    reported_defect_pct: number | null;
  }>;
  downtime: Array<{
    date: string;
    area: string;
    equipment: string | null;
    reason_code: string;
    reason_text_src: string;
    duration_min: number;
    criticality: string | null;
    capacity_loss_units: number | null;
  }>;
  plan: {
    plant_target: number;
    line_model_total: number;
    gap: number;
    rows: Array<{ model: string; model_src: string; qty: number }>;
    naive_month_projection: number;
    required_rate_per_shift_target: number;
    required_rate_per_shift_line_plan: number;
    mean_sustainable_rate_per_shift: number;
  };
  alerts: Array<{ date: string | null; entity: string; rule_id: string; severity: Severity; value: unknown }>;
  data_quality_issues: Array<{
    date: string | null;
    entity: string;
    rule_id: string;
    severity: Severity;
    details: Record<string, unknown>;
  }>;
  constraints_parsed: Record<string, number>;
  constraint_checks: Array<{ key: string; value: number; source: string; matches: boolean; configured: number | null }>;
  bottleneck_aggregate: { overall: string | null; shifting: boolean; by_day: Record<string, string> };
  flow?: Record<string, Record<string, number>>;
  warnings: string[];
}

// ------------------------------------------------------------------ demo console (/sim/*)

export interface SimStatus {
  state: string;
  mode: string;
  ready: boolean;
  speed: number;
  speed_presets: number[];
  paused: boolean;
  epoch: number;
  seed: number;
  demo_start: string;
  last_reset: string | null;
  plant_time: string;
  shift: { date: string; code: string } | null;
  scenarios: Array<{ scenario_id: string | null; type: string; at: string; status: string }>;
}
export interface SimScenario {
  id: string;
  name_ru: string;
  name_kk: string | null;
  at_min: number | null;
  inject: Record<string, unknown>;
}
