"""Models for the tag map — OPC UA / MQTT integration contract (SPEC §6.7–6.8, §7.1).

Files: ``tag_map.example.yaml`` (schema example, always validated by tests),
``tag_map.demo.yaml`` (generated by ``make tagmap``), ``tag_map.yaml`` (filled in on a pilot).
"""

from __future__ import annotations

from typing import Annotated, Literal

from pydantic import StringConstraints, field_validator, model_validator

from twin_core.config.common import Code, Ident, NonEmptyStr, PositiveFloat, StrictModel
from twin_core.domain import EquipmentState

EQUIPMENT_VARIABLES = frozenset({"state", "state_since", "alarm", "alarm_code"})
"""Standard per-equipment variables (SPEC §6.7) besides the telemetry signals of its type."""

LINE_VARIABLES = frozenset(
    {
        "state",
        "good_count",
        "reject_count",
        "produced_count",
        "last_body_id",
        "last_product",
        "cycle_time_s",
    }
)
BUFFER_VARIABLES = frozenset({"level", "capacity"})
PRODUCT_VARIABLES = frozenset({"kits"})
SITE_VARIABLES = frozenset({"clock", "shift", "speed"})

FORBIDDEN_SIGNALS = frozenset({"degradation"})
"""Simulator oracle; analytics must never subscribe to it (FR-SIM-02, T-RO)."""

TARGET_FIELDS = ("equipment", "line", "buffer", "product", "site")


class OpcUaSecurity(StrictModel):
    mode: Literal["None", "Sign", "SignAndEncrypt"]
    policy: NonEmptyStr


class TagNode(StrictModel):
    """One OPC UA node mapped to exactly one model entity and signal."""

    node_id: Annotated[str, StringConstraints(pattern=r"^(ns=\d+;)?[isgb]=.+$")]
    equipment: Code | None = None
    line: Code | None = None
    buffer: Code | None = None
    product: Code | None = None
    site: Code | None = None
    signal: Ident

    @model_validator(mode="after")
    def _one_target(self) -> TagNode:
        targets = [name for name in TARGET_FIELDS if getattr(self, name) is not None]
        if len(targets) != 1:
            found = ", ".join(targets) or "none"
            raise ValueError(
                f"a node must reference exactly one of {', '.join(TARGET_FIELDS)} (found: {found})"
            )
        return self

    @field_validator("signal")
    @classmethod
    def _not_oracle(cls, value: str) -> str:
        if value in FORBIDDEN_SIGNALS:
            raise ValueError(
                f"signal '{value}' is the simulator's hidden oracle and must not be mapped "
                "(FR-SIM-02)"
            )
        return value

    @property
    def target(self) -> tuple[str, str]:
        """``(entity kind, code)`` this node maps to."""
        for name in TARGET_FIELDS:
            value = getattr(self, name)
            if value is not None:
                return name, value
        raise AssertionError("validated node without target")  # pragma: no cover


class OpcUaMap(StrictModel):
    endpoint: Annotated[str, StringConstraints(pattern=r"^opc\.tcp://.+")]
    security: OpcUaSecurity
    namespace_uri: NonEmptyStr
    publishing_interval_ms: PositiveFloat
    nodes: list[TagNode] = []
    state_enum: dict[int, EquipmentState]
    """Raw integer value of a ``State`` tag -> model state (SPEC §5.3)."""

    @field_validator("state_enum")
    @classmethod
    def _bijective(cls, value: dict[int, EquipmentState]) -> dict[int, EquipmentState]:
        seen: dict[EquipmentState, int] = {}
        for raw, state in value.items():
            if state in seen:
                raise ValueError(f"state {state} is mapped twice (values {seen[state]} and {raw})")
            seen[state] = raw
        return value


class MqttMap(StrictModel):
    url: Annotated[str, StringConstraints(pattern=r"^mqtts?://.+")]
    topic_root: NonEmptyStr
    payload: Literal["json"]


class TagMapConfig(StrictModel):
    """Root of a tag map file."""

    version: Literal[1]
    opcua: OpcUaMap
    mqtt: MqttMap


__all__ = [
    "BUFFER_VARIABLES",
    "EQUIPMENT_VARIABLES",
    "FORBIDDEN_SIGNALS",
    "LINE_VARIABLES",
    "PRODUCT_VARIABLES",
    "SITE_VARIABLES",
    "MqttMap",
    "OpcUaMap",
    "OpcUaSecurity",
    "TagMapConfig",
    "TagNode",
]
